import type { NextPage } from 'next'
import Head from 'next/head'
import {
  Text,
  Icon,
  Image,
  Divider,
  Heading,
} from '@chakra-ui/react';
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>COVID Visualization in Malaysia</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <Heading>Hello World!</Heading>
      </main>
    </div>
  )
}

export default Home