import type { NextPage } from 'next'
import Head from 'next/head'
import {
  Text,
  Image,
  Divider,
  Heading,
  Flex,
  VStack,
  Box,
  Spacer,
  Icon
} from '@chakra-ui/react';
import { useColorMode } from '@chakra-ui/react';
import { IconButton } from '@chakra-ui/react';
import {IoSunny, IoMoon} from 'react-icons/io5';
import {FaSun, FaMoon} from 'react-icons/fa';
import { useState } from 'react';

import Map from '../src/components/Map';

const Home: NextPage = () => {

  const {toggleColorMode} = useColorMode();
  const [toggle, setToggle] = useState<boolean>(false);

  return (
    <VStack paddingX={10} paddingY={5}>
      <Head>
        <title>COVID in Malaysia</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Flex w="100%">
        <Heading size="3xl" fontWeight='semibold' >COVID In Malaysia</Heading>
        <Spacer></Spacer>
        <Text>Set Color Mode</Text>
        <Box
        cursor={"pointer"}
        onClick={() => {
          toggleColorMode();
          setToggle(!toggle);
        }}
      >
        {toggle ? <IoMoon size={20} /> : <IoSunny size={20}/>}
      </Box>
      </Flex>
      <Flex w="100%">
        <Heading size="xl">Sub Title</Heading>
      </Flex>
      <Map />
    </VStack>
  )
}

export default Home